export type Provider="openai"|"anthropic"|"gemini"|"groq"|"openrouter"|"azure_openai"|"aws_bedrock";
export interface UsageEvent{provider:Provider;model:string;prompt_tokens:number;completion_tokens:number;idempotency_key:string;provider_request_id?:string;attributed_user_id?:string;project?:string;agent?:string;environment?:string;latency_ms?:number;timestamp?:string}
export interface PolicyRequest{provider:Provider;model:string;estimated_prompt_tokens?:number;estimated_completion_tokens?:number;user_id?:string}
export interface PolicyDecision{allowed:boolean;blocked:boolean;reason:string;remaining_budget:number|null;current_usage:number}
export interface TokenWatchOptions{apiKey:string;baseUrl?:string;timeoutMs?:number;fetch?:typeof fetch}
export class TokenWatchError extends Error{constructor(message:string,public readonly status:number,public readonly code?:string){super(message);this.name="TokenWatchError"}}
export class TokenWatch{private readonly base:string;private readonly timeout:number;private readonly requestFetch:typeof fetch;constructor(private readonly options:TokenWatchOptions){if(!options.apiKey.startsWith("tw_live_"))throw new Error("A TokenWatch SDK key is required");this.base=(options.baseUrl||"https://tokenwatch-backend.vercel.app").replace(/\/$/,"");this.timeout=options.timeoutMs||10000;this.requestFetch=options.fetch||fetch}
 private async request<T>(path:string,body:unknown):Promise<T>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeout);try{const response=await this.requestFetch(this.base+path,{method:"POST",headers:{"content-type":"application/json","x-tokenwatch-key":this.options.apiKey},body:JSON.stringify(body),signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new TokenWatchError(data?.detail?.code||data?.detail||"TokenWatch request failed",response.status,data?.detail?.code);return data as T}finally{clearTimeout(timer)}}
 ingest(event:UsageEvent){return this.request<{usage_id:string;duplicate:boolean;calculated_cost:string;currency:string}>("/v1/ingest/usage",event)}
 checkPolicy(request:PolicyRequest){return this.request<PolicyDecision>("/policy/check",request)}}
